// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import WaterEffectController from "./water_effect_controller"
application.register("water-effect", WaterEffectController)

import XShareController from "./x_share_controller"
application.register("x-share", XShareController)

import ChartDebugController from "./chart_debug_controller"
application.register("chart", ChartDebugController)
