// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import WaterEffectController from "./water_effect_controller"
application.register("water-effect", WaterEffectController)

import XShareController from "./x_share_controller"
application.register("x-share", XShareController)

import ChartDebugController from "./chart_debug_controller"
application.register("chart", ChartDebugController)


import WeekdayChartController from "./weekday_chart_controller"
application.register("weekday-chart", WeekdayChartController)

import HeatmapController from "./heatmap_controller"
application.register("heatmap", HeatmapController)

import CalendarController from "./calendar_controller"
application.register("calendar", CalendarController)


import ChartPeriodController from "./chart_period_controller"
application.register("chart-period", ChartPeriodController)

import DiaryViewController from "./diary_view_controller"
application.register("diary-view", DiaryViewController)

import TutorialController from "./tutorial_controller"
application.register("tutorial", TutorialController)

import UserDeleteController from "./user_delete_controller"
application.register("user-delete", UserDeleteController)

import LoadingController from "./loading_controller"
application.register("loading", LoadingController)

import AiLoadingController from "./ai_loading_controller"
application.register("ai-loading", AiLoadingController)

import ModalController from "./modal_controller"
application.register("modal", ModalController)

import GithubUploadController from "./github_upload_controller"
application.register("github-upload", GithubUploadController)

import ThemeController from "./theme_controller"
application.register("theme", ThemeController)
