# RuboCop configuration for Programming Diary

plugins:
  - rubocop-rails
  - rubocop-performance
  - rubocop-rspec

inherit_gem:
  rubocop-rails-omakase: rubocop.yml

AllCops:
  TargetRubyVersion: 3.2
  NewCops: enable
  Exclude:
    - 'bin/**/*'
    - 'config/**/*'
    - 'db/**/*'
    - 'lib/tasks/**/*'
    - 'node_modules/**/*'
    - 'public/**/*'
    - 'storage/**/*'
    - 'tmp/**/*'
    - 'vendor/**/*'
    - 'Gemfile'
    - 'Rakefile'
    - 'config.ru'

# Rails specific configurations
Rails:
  Enabled: true

# Layout configurations
Layout/LineLength:
  Max: 120
  Exclude:
    - 'config/routes.rb'

# Style configurations
Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

# Disable some strict rules for this project
Rails/I18nLocaleTexts:
  Enabled: false

Rails/HasManyOrHasOneDependent:
  Enabled: false

# RSpec specific configurations
RSpec/ExampleLength:
  Max: 20

RSpec/MultipleExpectations:
  Max: 5

RSpec/NestedGroups:
  Max: 4

RSpec/AnyInstance:
  Enabled: false
