development:
  cloud_name: <%= Rails.application.credentials.dig(:claudinary, :cloud_name) %>
  api_key: <%= Rails.application.credentials.dig(:claudinary, :api_key) %>
  api_secret: <%= Rails.application.credentials.dig(:claudinary, :api_secret) %>
  secure: true

production:
  cloud_name: <%= Rails.application.credentials.dig(:claudinary, :cloud_name) %>
  api_key: <%= Rails.application.credentials.dig(:claudinary, :api_key) %>
  api_secret: <%= Rails.application.credentials.dig(:claudinary, :api_secret) %>
  secure: true
